# Generated by Django 5.0.6 on 2024-10-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_userprofile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
