# Generated by Django 5.0.6 on 2024-11-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_userprofile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="program_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
