# Generated by Django 5.0.6 on 2024-11-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_userprofile_program_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="cover_image",
            field=models.CharField(default="img-cover.png", max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_image",
            field=models.CharField(default="img-profile.png", max_length=50),
        ),
    ]
