# Generated by Django 5.0.6 on 2024-11-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("threads", "0002_alter_incident_options_alter_reply_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="avatar",
            field=models.CharField(max_length=255),
        ),
    ]
