# Generated by Django 5.0.6 on 2024-11-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("safetymonitoring", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
