# Generated by Django 5.0.6 on 2024-11-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("safetymonitoring", "0003_remove_incident_reported_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="severity",
            field=models.CharField(
                choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")],
                default="Low",
                max_length=10,
            ),
        ),
    ]
