# Generated by Django 5.0.6 on 2024-10-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Enter a short title for the event", max_length=150
                    ),
                ),
                ("date", models.DateField(help_text="Enter the date of the event")),
                ("start_time", models.TimeField(help_text="Event start time")),
                ("end_time", models.TimeField(help_text="Event end time")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional: Brief description of the event",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        help_text="Indicate if the event is public or private",
                        max_length=7,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when this event was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when this event was last updated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Calendar Event",
                "verbose_name_plural": "Academic Calendar Events",
                "ordering": ["date", "start_time"],
            },
        ),
    ]
