# Generated by Django 5.0.6 on 2024-10-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academicEvents", "0002_academiccalendar_address_academiccalendar_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="academiccalendar",
            name="is_online",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
