# Generated by Django 5.0.6 on 2024-10-28 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0002_remove_program_duration_remove_program_level"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="course",
            name="year",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="semester",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enrollment",
            name="year",
            field=models.IntegerField(default="1"),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={("user", "course", "year", "semester")},
        ),
    ]
