# Generated by Django 5.0.6 on 2024-10-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0003_alter_enrollment_unique_together_course_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="course_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
