# Generated by Django 5.0.6 on 2024-10-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0004_enrollment_course_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="course_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
