# Generated by Django 5.0.6 on 2024-10-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0005_enrollment_course_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="scheduled",
            field=models.CharField(blank=True, default=1, max_length=50, null=True),
        ),
    ]
