# Generated by Django 5.0.6 on 2024-11-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0008_alter_activities_user_alter_instructor_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="rfid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
