# Generated by Django 5.0.6 on 2024-11-06 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0010_enrollment_program"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="program",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.program",
            ),
            preserve_default=False,
        ),
    ]
