# Generated by Django 5.0.6 on 2024-11-06 09:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0011_alter_enrollment_program"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="program",
        ),
    ]
