# Generated by Django 5.0.6 on 2024-11-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0012_remove_enrollment_program"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="year",
            field=models.IntegerField(max_length=200),
        ),
    ]
