# Generated by Django 5.0.6 on 2024-11-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0015_activities_course_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="year",
            field=models.IntegerField(),
        ),
    ]
