# Generated by Django 5.0.6 on 2024-11-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_personalinfo_cover_image_personalinfo_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalinfo",
            name="cover_image",
            field=models.CharField(default="img-cover.png", max_length=255),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="profile_image",
            field=models.CharField(default="img-profile.png", max_length=255),
        ),
    ]
