# Generated by Django 5.0.6 on 2024-10-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="facilities",
            old_name="capcity",
            new_name="capacity",
        ),
        migrations.AlterField(
            model_name="facilities",
            name="facility_type",
            field=models.CharField(max_length=100),
        ),
    ]
