# Generated by Django 5.0.6 on 2024-11-01 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0002_rename_capcity_facilities_capacity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilities",
            name="capacity",
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name="FacilityBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("booking_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="facilities.facilities",
                    ),
                ),
            ],
        ),
    ]
