# Generated by Django 5.0.6 on 2024-11-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0003_alter_facilities_capacity_facilitybooking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facilitybooking",
            name="booking_date",
        ),
        migrations.RemoveField(
            model_name="facilitybooking",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="facilitybooking",
            name="start_time",
        ),
        migrations.AddField(
            model_name="facilitybooking",
            name="activity_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
