# Generated by Django 5.0.6 on 2024-11-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0004_remove_facilitybooking_booking_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilitybooking",
            name="activity_end_time",
            field=models.TimeField(default="02:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facilitybooking",
            name="activity_start_time",
            field=models.TimeField(default="12:00"),
            preserve_default=False,
        ),
    ]
