# Generated by Django 5.0.6 on 2024-11-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facilities", "0005_facilitybooking_activity_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facilitybooking",
            name="activity_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
