# Generated by Django 5.0.6 on 2024-10-31 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academics", "0007_activities"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hall", models.CharField(max_length=100)),
                ("date", models.DateField(blank=True, null=True)),
                ("time_start", models.TimeField()),
                ("time_end", models.TimeField()),
                ("recurring_days", models.JSONField(blank=True, null=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="academics.enrollment",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor_schedules",
                        to="academics.instructor",
                    ),
                ),
            ],
        ),
    ]
