# Generated by Django 5.0.6 on 2024-11-03 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courseschedules", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.CharField(max_length=50)),
                ("course_name", models.CharField(max_length=50)),
                ("course_hall", models.CharField(max_length=50)),
                ("marked_date", models.DateTimeField(auto_now_add=True)),
                ("day_of_class", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[("present", "Present"), ("absent", "Absent")],
                        max_length=10,
                    ),
                ),
                (
                    "check_in_method",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("rfid", "RFID"),
                            ("fingerprint", "Fingerprint"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="courseschedules.schedule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
