# Generated by Django 5.0.6 on 2024-11-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courseschedules", "0002_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="qr_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="qr_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="qr_session_key",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
