# Generated by Django 5.0.6 on 2024-11-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "courseschedules",
            "0003_schedule_qr_expires_at_schedule_qr_generated_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="check_in_method",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("rfid", "RFID"),
                    ("fingerprint", "Fingerprint"),
                    ("qrCode", "Qrcode"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="marked_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
