# Generated by Django 5.0.6 on 2024-11-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courseschedules", "0004_alter_attendance_check_in_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="semester",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="year",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
