# Generated by Django 5.0.6 on 2024-11-08 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0016_alter_course_year"),
        ("courseschedules", "0005_attendance_semester_attendance_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.course",
            ),
        ),
    ]
