# Generated by Django 5.0.6 on 2024-11-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courseschedules", "0006_attendance_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="enrollment",
        ),
        migrations.AddField(
            model_name="schedule",
            name="course_id",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
