# Generated by Django 5.0.6 on 2024-11-17 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0017_alter_instructor_expertise"),
        ("courseschedules", "0007_remove_schedule_enrollment_schedule_course_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="academics.enrollment",
            ),
        ),
    ]
