# Generated by Django 5.0.6 on 2024-10-28 14:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hall_name", models.CharField(max_length=100, unique=True)),
                ("hall_capacity", models.PositiveIntegerField()),
                ("hall_description", models.TextField(blank=True, null=True)),
                ("hall_number", models.CharField(max_length=10, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
