# Generated by Django 5.0.6 on 2024-10-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Halls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hall",
            name="booked",
            field=models.BooleanField(default=False),
        ),
    ]
